### PR TITLE
docs(es): Jan 1 - Jan 9

### PR DESCRIPTION
**Pull request by David-Pena**
Commits translated
- [X] https://github.com/vuejs/docs/commit/051d9a85b8814779c0d829dd2d8138bb558eac18
- [X] https://github.com/vuejs/docs/commit/c598a04f0c5102c266b2a2a394c9e75c02189236
- [X] https://github.com/vuejs/docs/commit/3c3add3252a159f0098f714bc0628c8e5463c862
- [X] https://github.com/vuejs/docs/commit/6f19ed7b0923e6ca70d8be39b235f9b8f6cd30d3
- [X] https://github.com/vuejs/docs/commit/6d91d775d8bf6a18c4df4253fb295d1cfc5a7d32
- [X] https://github.com/vuejs/docs/commit/8f5dde5f540d8a9990f61b682c5916e85e4ced15
- [X] https://github.com/vuejs/docs/commit/6d79dc9f72a9f4ea75909e1c026e1009c7c0a726
- [X] https://github.com/vuejs/docs/commit/fc57f696e90d8e66f094c04f08548a9677c2affa
- [X] https://github.com/vuejs/docs/commit/7cf1733489a522de2bb9c3617eb99723db3c85c7

### CODE REVIEW

**Review by glopzel — COMMENTED** [review]
LGTM

**Comment by David-Pena** [comment]
@mrcego this PR is ready to merge

**Review by mrcego — CHANGES_REQUESTED** [review]
Let's merge latest main branch changes please @David-Pena. Thanks

**Comment by David-Pena** [comment]
This PR is already updated and ready to be merged @mrcego

**Review by mrcego — APPROVED** [review]

**Pull request merged**
