### PR TITLE
docs(es): Dec 29 - Dec 31

### PR DESCRIPTION
**Pull request by David-Pena**
Commits translated
- [X] https://github.com/vuejs/docs/commit/5cbf0bff51a01880c07909d6972d5f1cdf874bd9
- [X] https://github.com/vuejs/docs/commit/7bfcc8a8ae84a501642baff9efb0f392fd87f59f
- [X] https://github.com/vuejs/docs/commit/b621c6d7ed18b72febefa87486b27e651b7ed94d
- [X] https://github.com/vuejs/docs/commit/9f8e5b1008b0f63aec6585eedb078728982f4ed3 
- [X] https://github.com/vuejs/docs/commit/e19c6be837f13ee1b1082688b6039a847d8e2524

### CODE REVIEW

**Comment by David-Pena** [comment]
Please review @mrcego @glopzel

**Comment by mrcego** [comment]
@David-Pena Have you already merged main branch with yours? If answer is no, please do it. Thanks.

**Comment by David-Pena** [comment]
Yes I already did @mrcego in here https://github.com/icarusgk/vuejs-spanish-docs/pull/77/commits/20e4b701b3ff794903ca8cfbf810a4e5f7b05a56

**Review by glopzel — COMMENTED** [review]
LGTM

**Review by mrcego — APPROVED** [review]

**Pull request merged**
